### ISSUE TITLE
控件的 visibility 属性不能设置为gone

### ISSUE THREAD

**Issue by tlemar** [androiddevelop/AlignTextView#6]
在将控件的visiblity属性设置为gone 之后，程序会崩溃。错误原因如下：
java.lang.StringIndexOutOfBoundsException: length=189; regionStart=0; regionLength=-1

at java.lang.AbstractStringBuilder.startEndAndLength(AbstractStringBuilder.java:211)
at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:616)
at java.lang.StringBuilder.substring(StringBuilder.java:44)
at me.codeboy.android.aligntextview.CBAlignTextView.processLine(CBAlignTextView.java:174)

**Comment by androiddevelop** [comment]
已修正，2.1.0版本

谢谢
